package com.desarrollo.enumerados;

public enum TipoMedidaUnidad {
	MILIGRAMOS, GRRAMOS, KILOGRAMOS, MILILITROS, CENTILITROS, LITROS, DECALITROS, HECTOLITROS, KILOLITROS, MILIMETROSCUBICOS, DECIMETROSCUBICOS, CENTIMETROSCUBICOS, METROSCUBICOS, DECAMETROSCUBICOS, HECTOMETROSCUBICOS, KILOMETROSCUBICOS

}
